// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: watermark.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartialWatermark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idle      bool  `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	Watermark int64 `protobuf:"varint,2,opt,name=watermark,proto3" json:"watermark,omitempty"`
}

func (x *PartialWatermark) Reset() {
	*x = PartialWatermark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watermark_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialWatermark) ProtoMessage() {}

func (x *PartialWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_watermark_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialWatermark.ProtoReflect.Descriptor instead.
func (*PartialWatermark) Descriptor() ([]byte, []int) {
	return file_watermark_proto_rawDescGZIP(), []int{0}
}

func (x *PartialWatermark) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *PartialWatermark) GetWatermark() int64 {
	if x != nil {
		return x.Watermark
	}
	return 0
}

type CombineWatermark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idle              bool                `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	CombinedWatermark int64               `protobuf:"varint,2,opt,name=combinedWatermark,proto3" json:"combinedWatermark,omitempty"`
	PartialWatermarks []*PartialWatermark `protobuf:"bytes,3,rep,name=partialWatermarks,proto3" json:"partialWatermarks,omitempty"`
}

func (x *CombineWatermark) Reset() {
	*x = CombineWatermark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watermark_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombineWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombineWatermark) ProtoMessage() {}

func (x *CombineWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_watermark_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombineWatermark.ProtoReflect.Descriptor instead.
func (*CombineWatermark) Descriptor() ([]byte, []int) {
	return file_watermark_proto_rawDescGZIP(), []int{1}
}

func (x *CombineWatermark) GetIdle() bool {
	if x != nil {
		return x.Idle
	}
	return false
}

func (x *CombineWatermark) GetCombinedWatermark() int64 {
	if x != nil {
		return x.CombinedWatermark
	}
	return 0
}

func (x *CombineWatermark) GetPartialWatermarks() []*PartialWatermark {
	if x != nil {
		return x.PartialWatermarks
	}
	return nil
}

var File_watermark_proto protoreflect.FileDescriptor

var file_watermark_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x44, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c,
	0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x98, 0x01, 0x0a, 0x10,
	0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x69, 0x64, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64,
	0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x42, 0x0a, 0x11, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x61, 0x74,
	0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d,
	0x61, 0x72, 0x6b, 0x52, 0x11, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x57, 0x61, 0x74, 0x65,
	0x72, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_watermark_proto_rawDescOnce sync.Once
	file_watermark_proto_rawDescData = file_watermark_proto_rawDesc
)

func file_watermark_proto_rawDescGZIP() []byte {
	file_watermark_proto_rawDescOnce.Do(func() {
		file_watermark_proto_rawDescData = protoimpl.X.CompressGZIP(file_watermark_proto_rawDescData)
	})
	return file_watermark_proto_rawDescData
}

var file_watermark_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_watermark_proto_goTypes = []interface{}{
	(*PartialWatermark)(nil), // 0: pb.PartialWatermark
	(*CombineWatermark)(nil), // 1: pb.CombineWatermark
}
var file_watermark_proto_depIdxs = []int32{
	0, // 0: pb.CombineWatermark.partialWatermarks:type_name -> pb.PartialWatermark
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_watermark_proto_init() }
func file_watermark_proto_init() {
	if File_watermark_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watermark_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialWatermark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watermark_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombineWatermark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watermark_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watermark_proto_goTypes,
		DependencyIndexes: file_watermark_proto_depIdxs,
		MessageInfos:      file_watermark_proto_msgTypes,
	}.Build()
	File_watermark_proto = out.File
	file_watermark_proto_rawDesc = nil
	file_watermark_proto_goTypes = nil
	file_watermark_proto_depIdxs = nil
}
